import { Editor } from "@tinymce/tinymce-react";

const EditorTiny = ({ editorRef , checkEdit, initContent}) => {
    return (
        <Editor
            apiKey="2fbonljqeyt6v92j1jnq0szb9xelpoomqz7etfuj3nzf3l8u"
            onInit={(evt, editor) => (editorRef.current = editor)}
            initialValue={checkEdit ? (initContent)  : ""}
            init={{
                selector: "textarea",
                plugins:
                    "anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount linkchecker  textcolor pageembed",
                toolbar:
                    "undo redo |  fontsize | bold italic underline  forecolor backcolor | link image media table mergetags | addcomment showcomments | spellcheckdialog a11ycheck typography | align lineheight |  numlist bullist indent outdent | emoticons charmap | removeformat codesample pageembed",
                content_style:
                    "body { background-color: #1A1A1A;color: white;  }",
                codesample_global_prismjs: true,
                codesample_languages: [
                    { text: "HTML/XML", value: "markup" },
                    {
                        text: "JavaScript",
                        value: "javascript",
                    },
                    { text: "CSS", value: "css" },
                    { text: "PHP", value: "php" },
                    { text: "Ruby", value: "ruby" },
                    { text: "Python", value: "python" },
                    { text: "Java", value: "java" },
                    { text: "C", value: "c" },
                    { text: "C#", value: "csharp" },
                    { text: "C++", value: "cpp" },
                    { text: "CMD", value: "cmd" },

                ],
                textcolor_map: [
                    "000000",
                    "Black",
                    "993300",
                    "Burnt orange",
                    "333300",
                    "Dark olive",
                    "003300",
                    "Dark green",
                    "003366",
                    "Dark azure",
                    "000080",
                    "Navy Blue",
                    "333399",
                    "Indigo",
                    "333333",
                    "Very dark gray",
                    "800000",
                    "Maroon",
                    "FF6600",
                    "Orange",
                    "808000",
                    "Olive",
                    "008000",
                    "Green",
                    "008080",
                    "Teal",
                    "0000FF",
                    "Blue",
                    "666699",
                    "Grayish blue",
                    "808080",
                    "Gray",
                    "FF0000",
                    "Red",
                    "FF9900",
                    "Amber",
                    "99CC00",
                    "Yellow green",
                    "339966",
                    "Sea green",
                    "33CCCC",
                    "Turquoise",
                    "3366FF",
                    "Royal blue",
                    "800080",
                    "Purple",
                    "999999",
                    "Medium gray",
                    "FF00FF",
                    "Magenta",
                    "FFCC00",
                    "Gold",
                    "FFFF00",
                    "Yellow",
                    "00FF00",
                    "Lime",
                    "00FFFF",
                    "Aqua",
                    "00CCFF",
                    "Sky blue",
                    "993366",
                    "Red violet",
                    "FFFFFF",
                    "White",
                    "FF99CC",
                    "Pink",
                    "FFCC99",
                    "Peach",
                    "FFFF99",
                    "Light yellow",
                    "CCFFCC",
                    "Pale green",
                    "CCFFFF",
                    "Pale cyan",
                    "99CCFF",
                    "Light sky blue",
                    "CC99FF",
                    "Plum",
                ],
                textcolor_rows: "7",
            }}
        />
    );
};

export default EditorTiny;
