name: Node.js CI

on:
  push:
    branches:
      - master
  # pull_request:
  #   branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    strategy: #build
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install yarn
        working-directory: ./API
        run: |
          npm install --global yarn
          yarn
          sudo npm install pm2 -g
          cp .env.copy .env
          cd /src
          pm2 start app.js


