name: Node.js CI

on:
  push:
    branches:
      - master
  # pull_request:
  #   branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    strategy: #build
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: build API
        working-directory: ./API
        run: |
          npm install
          cp .env.copy .env
          sudo su
          chmod -R 777 .env
          pm2 restart notesAPI
      # - name: build UI
      #   working-directory: ./UI
      #   run: |
      #     npm install
      #     npm install yarn
      #     cp .env.copy .env
      #     sed -i 's/REACT_APP_ENVIRONMENT=dev/REACT_APP_ENVIRONMENT=production/g' .env
      #     yarn run build


