name: Node.js CI

on:
  push:
    branches:
      - master
  # pull_request:
  #   branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    strategy: #build
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: build API
        working-directory: ./API
        run: |
          npm install
          sudo su
          npm install pm2 -g
          cp .env.copy .env
          pm2 reload src/app.js
      - name: build UI
        working-directory: ./UI
        run: |
          npm install
          cp .env.copy .env
          sudo su
          sed -i 's/REACT_APP_ENVIRONMENT=dev/REACT_APP_ENVIRONMENT=production/g' .env
          npm run build


